### ISSUE TITLE
Erreur pour l'exemple de changement de langue

### ISSUE THREAD

**Issue by tetue** [DISIC/guide-contribuer_accessible#10]
L'exemple donné dans la « fiche 9 : Textes multilingues » est incorrect.

En effet, le tag SPIP `<multi>` ne sert à signaler un changement de langue du texte, mais à TRADUIRE, plus précisément à fournir plusieurs traductions, qui seront affichées par SPIP selon le contexte de langue. Par exemple : `<multi>[fr]Aide[en]Help[es]Ayudar</multi>` affichera « Aide » sur une page rédigée en français, mais « Help » sur une page rédigée en anglais, etc.

Pour signaler un changement de langue au sein d'un texte, il convient d'utiliser l'attribut `lang`, dans SPIP comme ailleurs. Soit : « `Les images du <span lang="en">slider</span>` » ou plutôt « `Les images du <i lang="en">slider</i>` » puisqu'en typographie française (et conformément à la sémantique de l'élément HTML `<i>`) les mots d'origine étrangère se distinguent d'italique.

**Comment by tetue** [comment]
Précision : l'usage décrit n'est pas celui natif de [`<multi>` dans SPIP](http://programmer.spip.net/Les-Polyglottes-multi) mais un [usage détourné de `<multi>` par un plugin](http://contrib.spip.net/Bouton-Changement-de-langue-pour-le-Porte-Plume). C'est donc fonctionnel, même si paradoxalement plus compliqué que du HTML pur.
On peut donc conserver l'exemple, en précisant bien qu'il s'agit d'un SPIP modifié par un plugin.
Mais mieux vaut certainement recommander l'usage de l'attribut HTML lang, plus générique.

**Comment by Etat-Plateforme** [comment]
Bonjour et merci pour votre aide.

Nous avons pris en compte votre remarque que nous intègrerons dans la mise à jour prévue suite à la publication du RGAA v3 2016.
